<?php

declare(strict_types=1);

namespace miralsoft\docbee\api\DTO;

/**
 * Represents a Docbee MailParserConfig record.
 */
final class MailParserConfigDTO extends AbstractDTO
{
    public function __construct(
        /** Unique identifier representing a specific mailParserConfig */
        private readonly ?int $id,
        /** REST API Link */
        private readonly ?string $link,
        /** flag to allow all certificates */
        private ?string $allowAllCertificates,
        /** client id */
        private ?string $clientId,
        /** client secret */
        private ?string $clientSecret,
        /** flag to filter autogenerated mails */
        private ?string $filterAutoGeneratedEmails,
        /** regex applied to the mail body to determine which mails to parse */
        private ?string $filterParseEmailRegex,
        /** regex applied to the mail subject to determine which mails to parse */
        private ?string $filterParseSubjectRegex,
        /** flag to filter autogenerated responses */
        private ?string $filterResponseAutoGeneratedEmails,
        /** regex applied to the mail body to detect autogenerated responses */
        private ?string $filterResponseEmailRegex,
        /** regex applied to the mail subject to detect autogenerated responses */
        private ?string $filterResponseSubjectRegex,
        /** host address */
        private ?string $host,
        /** folder name to move mails into */
        private ?string $moveFolderName,
        /** name */
        private ?string $name,
        /** password */
        private ?string $password,
        /** port */
        private ?int $port,
        /** processing mode */
        private ?string $processingMode,
        /** protocol */
        private ?string $protocol,
        /** sender email address */
        private ?string $senderMail,
        /** aliases for the sender mail seperated via ";" */
        private ?string $senderMailAliases,
        /** tenant id */
        private ?string $tenantId,
        /** username */
        private ?string $username,
        /** version name */
        private ?string $versionName
    ) {}

    #[\Override]
    public static function fromArray(array $data): static
    {
        return new self(
            id: self::toInt($data['id'] ?? null),
            link: self::toString($data['link'] ?? null),
            allowAllCertificates: self::toString($data['allowAllCertificates'] ?? null),
            clientId: self::toString($data['clientId'] ?? null),
            clientSecret: self::toString($data['clientSecret'] ?? null),
            filterAutoGeneratedEmails: self::toString($data['filterAutoGeneratedEmails'] ?? null),
            filterParseEmailRegex: self::toString($data['filterParseEmailRegex'] ?? null),
            filterParseSubjectRegex: self::toString($data['filterParseSubjectRegex'] ?? null),
            filterResponseAutoGeneratedEmails: self::toString($data['filterResponseAutoGeneratedEmails'] ?? null),
            filterResponseEmailRegex: self::toString($data['filterResponseEmailRegex'] ?? null),
            filterResponseSubjectRegex: self::toString($data['filterResponseSubjectRegex'] ?? null),
            host: self::toString($data['host'] ?? null),
            moveFolderName: self::toString($data['moveFolderName'] ?? null),
            name: self::toString($data['name'] ?? null),
            password: self::toString($data['password'] ?? null),
            port: self::toInt($data['port'] ?? null),
            processingMode: self::toString($data['processingMode'] ?? null),
            protocol: self::toString($data['protocol'] ?? null),
            senderMail: self::toString($data['senderMail'] ?? null),
            senderMailAliases: self::toString($data['senderMailAliases'] ?? null),
            tenantId: self::toString($data['tenantId'] ?? null),
            username: self::toString($data['username'] ?? null),
            versionName: self::toString($data['versionName'] ?? null)
        );
    }

    #[\Override]
    public function toArray(): array
    {
        return array_filter([
            'allowAllCertificates' => $this->allowAllCertificates,
            'clientId' => $this->clientId,
            'clientSecret' => $this->clientSecret,
            'filterAutoGeneratedEmails' => $this->filterAutoGeneratedEmails,
            'filterParseEmailRegex' => $this->filterParseEmailRegex,
            'filterParseSubjectRegex' => $this->filterParseSubjectRegex,
            'filterResponseAutoGeneratedEmails' => $this->filterResponseAutoGeneratedEmails,
            'filterResponseEmailRegex' => $this->filterResponseEmailRegex,
            'filterResponseSubjectRegex' => $this->filterResponseSubjectRegex,
            'host' => $this->host,
            'moveFolderName' => $this->moveFolderName,
            'name' => $this->name,
            'password' => $this->password,
            'port' => $this->port,
            'processingMode' => $this->processingMode,
            'protocol' => $this->protocol,
            'senderMail' => $this->senderMail,
            'senderMailAliases' => $this->senderMailAliases,
            'tenantId' => $this->tenantId,
            'username' => $this->username,
            'versionName' => $this->versionName
        ], fn($v) => $v !== null);
    }

    public function getId(): ?int { return $this->id; }
    public function getLink(): ?string { return $this->link; }
    public function getAllowAllCertificates(): ?string { return $this->allowAllCertificates; }
    public function getClientId(): ?string { return $this->clientId; }
    public function getClientSecret(): ?string { return $this->clientSecret; }
    public function getFilterAutoGeneratedEmails(): ?string { return $this->filterAutoGeneratedEmails; }
    public function getFilterParseEmailRegex(): ?string { return $this->filterParseEmailRegex; }
    public function getFilterParseSubjectRegex(): ?string { return $this->filterParseSubjectRegex; }
    public function getFilterResponseAutoGeneratedEmails(): ?string { return $this->filterResponseAutoGeneratedEmails; }
    public function getFilterResponseEmailRegex(): ?string { return $this->filterResponseEmailRegex; }
    public function getFilterResponseSubjectRegex(): ?string { return $this->filterResponseSubjectRegex; }
    public function getHost(): ?string { return $this->host; }
    public function getMoveFolderName(): ?string { return $this->moveFolderName; }
    public function getName(): ?string { return $this->name; }
    public function getPassword(): ?string { return $this->password; }
    public function getPort(): ?int { return $this->port; }
    public function getProcessingMode(): ?string { return $this->processingMode; }
    public function getProtocol(): ?string { return $this->protocol; }
    public function getSenderMail(): ?string { return $this->senderMail; }
    public function getSenderMailAliases(): ?string { return $this->senderMailAliases; }
    public function getTenantId(): ?string { return $this->tenantId; }
    public function getUsername(): ?string { return $this->username; }
    public function getVersionName(): ?string { return $this->versionName; }
}