<?php

declare(strict_types=1);

namespace miralsoft\docbee\api\DTO;

/**
 * Represents a Docbee TicketMailParserConfig record.
 */
final class TicketMailParserConfigDTO extends AbstractDTO
{
    public function __construct(
        /** Unique identifier representing a specific ticketMailParserConfig */
        private readonly ?int $id,
        /** REST API Link */
        private readonly ?string $link,
        /** flag if the status should be changed, if a new auto generated message is set */
        private ?bool $changeStatusOnNewAutoGeneratedMessage,
        /** flag if the status should be changed, if a new message is set */
        private ?bool $changeStatusOnNewMessage,
        private mixed $department,
        /** enabled flag */
        private ?bool $enabled,
        /** regex to flag parsed messages as internal */
        private ?string $flagInternalRegex,
        /** flag to toggle this config as default */
        private ?bool $isDefault,
        /** flag to toggle this config as default for the TicketCategory */
        private ?bool $isDefaultForCategory,
        private mixed $mailParserConfig,
        /** name */
        private ?string $name,
        /** Status for newly created Tickets */
        private mixed $newStatus,
        /** @var TagDTO[]|null list of tags */
        private ?array $newTags,
        /** MessageTemplate for responses to newly created Tickets */
        private mixed $newTicketResponseMessageTemplate,
        /** flag to require a Mandant-Shortname in the Subject of the Mail */
        private ?bool $requireMandantShotnameInSubject,
        /** flag to search by DocBeeDocument ERP Reference-Number */
        private ?bool $searchByDocBeeDocumentErpReferenceNumber,
        /** flag to search by ERP Reference-Number */
        private ?bool $searchByErpReferenceNumber,
        /** flag to search by external Reference-Number */
        private ?bool $searchByExternalReferenceNumber,
        /** flag to search by Reference-Number */
        private ?bool $searchByReferenceNumber,
        /** flag to send response if new Ticket is created */
        private ?bool $sendNewResponse,
        /** flag to send response if a Ticket was updated */
        private ?bool $sendUpdateResponse,
        private mixed $ticketCategory,
        /** owner of the Ticket */
        private mixed $ticketOwner,
        /** Status for updated Tickets */
        private mixed $updateStatus,
        /** MessageTemplate for responses to updated Tickets */
        private mixed $updateTicketResponseMessageTemplate
    ) {}

    #[Override]
    public static function fromArray(array $data): static
    {
        return new self(
            id: self::toInt($data['id'] ?? null),
            link: self::toString($data['link'] ?? null),
            changeStatusOnNewAutoGeneratedMessage: isset($data['changeStatusOnNewAutoGeneratedMessage']) ? self::toBool($data['changeStatusOnNewAutoGeneratedMessage']) : null,
            changeStatusOnNewMessage: isset($data['changeStatusOnNewMessage']) ? self::toBool($data['changeStatusOnNewMessage']) : null,
            department: $data['department'] ?? null,
            enabled: isset($data['enabled']) ? self::toBool($data['enabled']) : null,
            flagInternalRegex: self::toString($data['flagInternalRegex'] ?? null),
            isDefault: isset($data['isDefault']) ? self::toBool($data['isDefault']) : null,
            isDefaultForCategory: isset($data['isDefaultForCategory']) ? self::toBool($data['isDefaultForCategory']) : null,
            mailParserConfig: $data['mailParserConfig'] ?? null,
            name: self::toString($data['name'] ?? null),
            newStatus: $data['newStatus'] ?? null,
            newTags: isset($data['newTags']) && is_array($data['newTags'])
                ? array_map(fn($x) => TagDTO::fromArray($x), $data['newTags'])
                : null,
            newTicketResponseMessageTemplate: $data['newTicketResponseMessageTemplate'] ?? null,
            requireMandantShotnameInSubject: isset($data['requireMandantShotnameInSubject']) ? self::toBool($data['requireMandantShotnameInSubject']) : null,
            searchByDocBeeDocumentErpReferenceNumber: isset($data['searchByDocBeeDocumentErpReferenceNumber']) ? self::toBool($data['searchByDocBeeDocumentErpReferenceNumber']) : null,
            searchByErpReferenceNumber: isset($data['searchByErpReferenceNumber']) ? self::toBool($data['searchByErpReferenceNumber']) : null,
            searchByExternalReferenceNumber: isset($data['searchByExternalReferenceNumber']) ? self::toBool($data['searchByExternalReferenceNumber']) : null,
            searchByReferenceNumber: isset($data['searchByReferenceNumber']) ? self::toBool($data['searchByReferenceNumber']) : null,
            sendNewResponse: isset($data['sendNewResponse']) ? self::toBool($data['sendNewResponse']) : null,
            sendUpdateResponse: isset($data['sendUpdateResponse']) ? self::toBool($data['sendUpdateResponse']) : null,
            ticketCategory: $data['ticketCategory'] ?? null,
            ticketOwner: $data['ticketOwner'] ?? null,
            updateStatus: $data['updateStatus'] ?? null,
            updateTicketResponseMessageTemplate: $data['updateTicketResponseMessageTemplate'] ?? null
        );
    }

    #[Override]
    public function toArray(): array
    {
        return array_filter([
            'changeStatusOnNewAutoGeneratedMessage' => $this->changeStatusOnNewAutoGeneratedMessage,
            'changeStatusOnNewMessage' => $this->changeStatusOnNewMessage,
            'department' => $this->department,
            'enabled' => $this->enabled,
            'flagInternalRegex' => $this->flagInternalRegex,
            'isDefault' => $this->isDefault,
            'isDefaultForCategory' => $this->isDefaultForCategory,
            'mailParserConfig' => $this->mailParserConfig,
            'name' => $this->name,
            'newStatus' => $this->newStatus,
            'newTags' => $this->newTags,
            'newTicketResponseMessageTemplate' => $this->newTicketResponseMessageTemplate,
            'requireMandantShotnameInSubject' => $this->requireMandantShotnameInSubject,
            'searchByDocBeeDocumentErpReferenceNumber' => $this->searchByDocBeeDocumentErpReferenceNumber,
            'searchByErpReferenceNumber' => $this->searchByErpReferenceNumber,
            'searchByExternalReferenceNumber' => $this->searchByExternalReferenceNumber,
            'searchByReferenceNumber' => $this->searchByReferenceNumber,
            'sendNewResponse' => $this->sendNewResponse,
            'sendUpdateResponse' => $this->sendUpdateResponse,
            'ticketCategory' => $this->ticketCategory,
            'ticketOwner' => $this->ticketOwner,
            'updateStatus' => $this->updateStatus,
            'updateTicketResponseMessageTemplate' => $this->updateTicketResponseMessageTemplate
        ], fn($v) => $v !== null);
    }

    public function getId(): ?int { return $this->id; }
    public function getLink(): ?string { return $this->link; }
    public function getChangeStatusOnNewAutoGeneratedMessage(): ?bool { return $this->changeStatusOnNewAutoGeneratedMessage; }
    public function getChangeStatusOnNewMessage(): ?bool { return $this->changeStatusOnNewMessage; }
    public function getDepartment(): mixed { return $this->department; }
    public function getEnabled(): ?bool { return $this->enabled; }
    public function getFlagInternalRegex(): ?string { return $this->flagInternalRegex; }
    public function getIsDefault(): ?bool { return $this->isDefault; }
    public function getIsDefaultForCategory(): ?bool { return $this->isDefaultForCategory; }
    public function getMailParserConfig(): mixed { return $this->mailParserConfig; }
    public function getName(): ?string { return $this->name; }
    public function getNewStatus(): mixed { return $this->newStatus; }
    public function getNewTags(): ?array { return $this->newTags; }
    public function getNewTicketResponseMessageTemplate(): mixed { return $this->newTicketResponseMessageTemplate; }
    public function getRequireMandantShotnameInSubject(): ?bool { return $this->requireMandantShotnameInSubject; }
    public function getSearchByDocBeeDocumentErpReferenceNumber(): ?bool { return $this->searchByDocBeeDocumentErpReferenceNumber; }
    public function getSearchByErpReferenceNumber(): ?bool { return $this->searchByErpReferenceNumber; }
    public function getSearchByExternalReferenceNumber(): ?bool { return $this->searchByExternalReferenceNumber; }
    public function getSearchByReferenceNumber(): ?bool { return $this->searchByReferenceNumber; }
    public function getSendNewResponse(): ?bool { return $this->sendNewResponse; }
    public function getSendUpdateResponse(): ?bool { return $this->sendUpdateResponse; }
    public function getTicketCategory(): mixed { return $this->ticketCategory; }
    public function getTicketOwner(): mixed { return $this->ticketOwner; }
    public function getUpdateStatus(): mixed { return $this->updateStatus; }
    public function getUpdateTicketResponseMessageTemplate(): mixed { return $this->updateTicketResponseMessageTemplate; }
}